replicaCount: 1

image:
  repository: bhindusuma/mywalletapp
  pullPolicy: Always
  tag: v0.0.8

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: NodePort
  port: 80
  nodePort: 32110

# env MUST be a map because the template iterates map keys/values
env:
  DJANGO_ALLOWED_HOSTS: "*"   # allow everywhere
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1"

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

# Ingress defaults (avoid nil pointer in templates)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# HPA defaults (avoid nil pointer in templates)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
