replicaCount: 1

image:
  repository: bhindusuma/mywalletapp
  pullPolicy: Always
  tag: v0.1.1

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: NodePort
  port: 80
  nodePort: 32110

# env MUST be a map because the template iterates map keys/values
env:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1"

resources: {}

# TCP probes to avoid app-returned 400/500 blocking readiness
livenessProbe:
  tcpSocket:
    port: http

readinessProbe:
  tcpSocket:
    port: http

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

# Ingress defaults
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

# HPA defaults
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
